### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by alecive** [SergKolo/launcher-list-indicator#3]
To be consistent with unity top bar icons, I suggest you to do a black and white version of the icon itself. Also, is your code able to use an svg icon? It would be much less blurry when rendered on the bar.

I can do that for you if you want.

**Comment by SergKolo** [comment]
@alecive Yes, it should be able to use svg icons. I can add an option for users to choose their own icon, if that would be better. Let me know if that would be a reasonable feature to include. The reason I decided to go with one single icon is because there's tons of themes for Unity and eventually the monochrome icon will come into conflict with one of them.

**Comment by SergKolo** [comment]
@alecive  I have added an option for changing icons under "Extras" menu, and also included monochrome icon version with the package.   I'll close the issue for now, let me know if you have any other suggestions

**Comment by alecive** [comment]
Mine was more on helping you find the best solution for everyone. I don't think many will use the feature to add custom icons. But that's okay :)
